### ISSUE TITLE
Add ability to to flag a runit service as 'down' to prevent runsv from automatically starting it

### ISSUE THREAD

**Issue by boldfield** [hw-cookbooks/runit#104]
Some services that can be managed by runit need to be able to be explicitly flagged as 'down' to prevent runsv from starting them automatically.  An example of this is runit managed ucarp VIPs. Please support adding `/etc/sv/<service>/down` files during service configuration.

**Comment by cwjohnston** [comment]
Added in #105, which was cherry-picked in commit 8a5f16067291663af217a2a65fc712a93bf060c8
