### ISSUE TITLE
How to use owner and group attribute?

### ISSUE THREAD

**Issue by HienNguyenAsnet** [hw-cookbooks/runit#111]
I setup runit service for vagrant.
I add config node attribute
```
"runit": {
      "owner": "vagrant",
      "group": "vagrant"
 }
```
But it not work. I ssh to vagrant and run
```
sv status nginx
```
I got an message ```unable to open supervise/ok: access denied```

**Comment by slyness** [comment]
Are you able to run the same command under sudo? `sudo sv status nginx`?

**Comment by HienNguyenAsnet** [comment]
I got an issue ```command not found``` when run service. I assume bash script run with sudo induced it. I try start service without sudo command.
Finally, I found the reason is run bash script file can't get source from .bashrc file. So I add source to bash script file and it work. Thanks.
