### ISSUE TITLE
on rhel7 or centos7 it doen't work

### ISSUE THREAD

**Issue by tzniuta** [hw-cookbooks/runit#113]
it doesn't create any vaild service.. 
is there any plan for rhel7 or centos7? 

```ruby
recipe: push-jobs::service_runit
  * runit_service[opscode-push-jobs-client] action start
    
    ================================================================================
    Error executing action `start` on resource 'runit_service[opscode-push-jobs-client]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /sbin/sv start /etc/service/opscode-push-jobs-client ----
    STDOUT: warning: /etc/service/opscode-push-jobs-client: unable to open supervise/ok: file does not exist
    STDERR: 
    ---- End output of /sbin/sv start /etc/service/opscode-push-jobs-client ----
    Ran /sbin/sv start /etc/service/opscode-push-jobs-client returned 1
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:176:in `start_service'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/push-jobs/recipes/service_runit.rb
    
     23: runit_service 'opscode-push-jobs-client' do
     24:   default_logger true
     25:   subscribes :restart, "template[#{PushJobsHelper.config_path}]"
     26:   action [ :enable, :start ]
     27:   retries 15
     28: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/push-jobs/recipes/service_runit.rb:23:in `from_file'
    
    runit_service("opscode-push-jobs-client") do
      provider Chef::Provider::Service::Runit
      action [:enable, :start]
      updated true
      supports {:restart=>true, :reload=>true, :status=>true}
      retries 15
      retry_delay 2
      default_guard_interpreter :default
      service_name "opscode-push-jobs-client"
      enabled true
      pattern "opscode-push-jobs-client"
      status_command "/sbin/sv status /etc/service"
      sv_bin "/sbin/sv"
      sv_dir "/etc/sv"
      service_dir "/etc/service"
      lsb_init_dir "/etc/init.d"
      log true
      default_logger true
      restart_on_update true
      run_template_name "opscode-push-jobs-client"
      log_template_name "opscode-push-jobs-client"
      check_script_template_name "opscode-push-jobs-client"
      finish_script_template_name "opscode-push-jobs-client"
      sv_templates true
      service_mirror # Declared in 
    
    service("opscode-push-jobs-client") do
      provider Chef::Provider::Service::Simple
      action [:nothing]
      supports {:restart=>true, :reload=>true, :status=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "opscode-push-jobs-client"
      pattern "opscode-push-jobs-client"
      start_command "/sbin/sv start /etc/service/opscode-push-jobs-client"
      stop_command "/sbin/sv stop /etc/service/opscode-push-jobs-client"
      status_command "/sbin/sv status /etc/service/opscode-push-jobs-client"
      restart_command "/sbin/sv restart /etc/service/opscode-push-jobs-client"
    end
    
      declared_type :runit_service
      cookbook_name "push-jobs"
      recipe_name "service_runit"
    end
    

Running handlers:
[2015-04-24T22:37:45+09:00] ERROR: Running exception handlers
Running handlers complete
[2015-04-24T22:37:45+09:00] ERROR: Exception handlers complete
[2015-04-24T22:37:45+09:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 2 resources updated in 94.366871368 seconds
[2015-04-24T22:37:45+09:00] ERROR: runit_service[opscode-push-jobs-client] (push-jobs::service_runit line 23) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /sbin/sv start /etc/service/opscode-push-jobs-client ----
STDOUT: warning: /etc/service/opscode-push-jobs-client: unable to open supervise/ok: file does not exist
STDERR: 
---- End output of /sbin/sv start /etc/service/opscode-push-jobs-client ----
Ran /sbin/sv start /etc/service/opscode-push-jobs-client returned 1

```

**Comment by cmluciano** [comment]
Support should be coming soon, The develop branch converge/test works on centos-7

**Comment by tzniuta** [comment]
@cmluciano  thank you for your reply, but it doesn't works

  * runit_service[opscode-push-jobs-client] action start
    
    ================================================================================
    Error executing action `start` on resource 'runit_service[opscode-push-jobs-client]'
    ================================================================================
    
    NoMethodError
    -------------
    No resource or method named `action_start' for `Chef::Provider::RunitService ""'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/push-jobs/recipes/service_runit.rb
    
     23: runit_service 'opscode-push-jobs-client' do
     24:   default_logger true
     25:   subscribes :restart, "template[#{PushJobsHelper.config_path}]"
     26:   action [ :enable, :start ]
     27:   retries 15
     28: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/push-jobs/recipes/service_runit.rb:23:in `from_file'
    
    runit_service("opscode-push-jobs-client") do
      provider Chef::Provider::RunitService
      action [:enable, :start]
      updated true
      supports {:restart=>true, :reload=>true, :status=>true}
      retries 15
      retry_delay 2
      default_guard_interpreter :default
      service_name "opscode-push-jobs-client"
      pattern "opscode-push-jobs-client"
      status_command "/sbin/sv status /etc/service"
      sv_bin "/sbin/sv"
      sv_dir "/etc/sv"
      service_dir "/etc/service"
      lsb_init_dir "/etc/init.d"
      log true
      default_logger true
      restart_on_update true
      run_template_name "opscode-push-jobs-client"
      log_template_name "opscode-push-jobs-client"
      check_script_template_name "opscode-push-jobs-client"
      finish_script_template_name "opscode-push-jobs-client"
      sv_templates true
      service_mirror # Declared in 
    
    service("opscode-push-jobs-client") do
      provider Chef::Provider::Service::Simple
      action [:nothing]
      supports {:restart=>true, :reload=>true, :status=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "opscode-push-jobs-client"
      pattern "opscode-push-jobs-client"
      start_command "/sbin/sv start /etc/service/opscode-push-jobs-client"
      stop_command "/sbin/sv stop /etc/service/opscode-push-jobs-client"
      status_command "/sbin/sv status /etc/service/opscode-push-jobs-client"
      restart_command "/sbin/sv restart /etc/service/opscode-push-jobs-client"
    end
    
      declared_type :runit_service
      cookbook_name "push-jobs"
      recipe_name "service_runit"
    end
    
  * runit_service[opscode-push-jobs-client] action restart
    
    ================================================================================
    Error executing action `restart` on resource 'runit_service[opscode-push-jobs-client]'
    ================================================================================
    
    NoMethodError
    -------------
    No resource or method named `action_restart' for `Chef::Provider::RunitService ""'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/push-jobs/recipes/service_runit.rb
    
     23: runit_service 'opscode-push-jobs-client' do
     24:   default_logger true
     25:   subscribes :restart, "template[#{PushJobsHelper.config_path}]"
     26:   action [ :enable, :start ]
     27:   retries 15
     28: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/push-jobs/recipes/service_runit.rb:23:in `from_file'
    
    runit_service("opscode-push-jobs-client") do
      provider Chef::Provider::RunitService
      action [:enable, :start]
      updated true
      supports {:restart=>true, :reload=>true, :status=>true}
      retries 15
      retry_delay 2
      default_guard_interpreter :default
      service_name "opscode-push-jobs-client"
      pattern "opscode-push-jobs-client"
      status_command "/sbin/sv status /etc/service"
      sv_bin "/sbin/sv"
      sv_dir "/etc/sv"
      service_dir "/etc/service"
      lsb_init_dir "/etc/init.d"
      log true
      default_logger true
      restart_on_update true
      run_template_name "opscode-push-jobs-client"
      log_template_name "opscode-push-jobs-client"
      check_script_template_name "opscode-push-jobs-client"
      finish_script_template_name "opscode-push-jobs-client"
      sv_templates true
      service_mirror # Declared in 
    
    service("opscode-push-jobs-client") do
      provider Chef::Provider::Service::Simple
      action [:nothing]
      supports {:restart=>true, :reload=>true, :status=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "opscode-push-jobs-client"
      pattern "opscode-push-jobs-client"
      start_command "/sbin/sv start /etc/service/opscode-push-jobs-client"
      stop_command "/sbin/sv stop /etc/service/opscode-push-jobs-client"
      status_command "/sbin/sv status /etc/service/opscode-push-jobs-client"
      restart_command "/sbin/sv restart /etc/service/opscode-push-jobs-client"
    end
    
      declared_type :runit_service
      cookbook_name "push-jobs"
      recipe_name "service_runit"
    end
    

Running handlers:
[2015-04-26T18:27:51+09:00] ERROR: Running exception handlers
Running handlers complete
[2015-04-26T18:27:51+09:00] ERROR: Exception handlers complete
[2015-04-26T18:27:51+09:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 22 resources updated in 166.727254159 seconds
[2015-04-26T18:27:51+09:00] ERROR: Chef::Exceptions::MultipleFailures
[2015-04-26T18:27:51+09:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by tzniuta** [comment]
hmm i'm testing on centos6.4 but it occurs same error 
is there no start action on runit cookbook? 

 * runit_service[opscode-push-jobs-client] action start
    
    ================================================================================
    Error executing action `start` on resource 'runit_service[opscode-push-jobs-client]'
    ================================================================================
    
    NoMethodError
    -------------
    No resource or method named `action_start' for `Chef::Provider::RunitService ""'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/push-jobs/recipes/service_runit.rb
    
     23: runit_service 'opscode-push-jobs-client' do
     24:   default_logger true
     25:   subscribes :restart, "template[#{PushJobsHelper.config_path}]"
     26:   action [ :enable, :start ]
     27:   retries 15
     28: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/push-jobs/recipes/service_runit.rb:23:in `from_file'
    
    runit_service("opscode-push-jobs-client") do
      provider Chef::Provider::RunitService
      action [:enable, :start]
      updated true
      supports {:restart=>true, :reload=>true, :status=>true}
      retries 15
      retry_delay 2
      default_guard_interpreter :default
      service_name "opscode-push-jobs-client"
      pattern "opscode-push-jobs-client"
      status_command "/sbin/sv status /etc/service"
      sv_bin "/sbin/sv"
      sv_dir "/etc/sv"
      service_dir "/etc/service"
      lsb_init_dir "/etc/init.d"
      log true
      default_logger true
      restart_on_update true
      run_template_name "opscode-push-jobs-client"
      log_template_name "opscode-push-jobs-client"
      check_script_template_name "opscode-push-jobs-client"
      finish_script_template_name "opscode-push-jobs-client"
      sv_templates true
      service_mirror # Declared in 
    
    service("opscode-push-jobs-client") do
      provider Chef::Provider::Service::Simple
      action [:nothing]
      supports {:restart=>true, :reload=>true, :status=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "opscode-push-jobs-client"
      pattern "opscode-push-jobs-client"
      start_command "/sbin/sv start /etc/service/opscode-push-jobs-client"
      stop_command "/sbin/sv stop /etc/service/opscode-push-jobs-client"
      status_command "/sbin/sv status /etc/service/opscode-push-jobs-client"
      restart_command "/sbin/sv restart /etc/service/opscode-push-jobs-client"
    end
    
      declared_type :runit_service
      cookbook_name "push-jobs"
      recipe_name "service_runit"
    end
    
  * runit_service[opscode-push-jobs-client] action restart
    
    ================================================================================
    Error executing action `restart` on resource 'runit_service[opscode-push-jobs-client]'
    ================================================================================
    
    NoMethodError
    -------------
    No resource or method named `action_restart' for `Chef::Provider::RunitService ""'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/push-jobs/recipes/service_runit.rb
    
     23: runit_service 'opscode-push-jobs-client' do
     24:   default_logger true
     25:   subscribes :restart, "template[#{PushJobsHelper.config_path}]"
     26:   action [ :enable, :start ]
     27:   retries 15
     28: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/push-jobs/recipes/service_runit.rb:23:in `from_file'
    
    runit_service("opscode-push-jobs-client") do
      provider Chef::Provider::RunitService
      action [:enable, :start]
      updated true
      supports {:restart=>true, :reload=>true, :status=>true}
      retries 15
      retry_delay 2
      default_guard_interpreter :default
      service_name "opscode-push-jobs-client"
      pattern "opscode-push-jobs-client"
      status_command "/sbin/sv status /etc/service"
      sv_bin "/sbin/sv"
      sv_dir "/etc/sv"
      service_dir "/etc/service"
      lsb_init_dir "/etc/init.d"
      log true
      default_logger true
      restart_on_update true
      run_template_name "opscode-push-jobs-client"
      log_template_name "opscode-push-jobs-client"
      check_script_template_name "opscode-push-jobs-client"
      finish_script_template_name "opscode-push-jobs-client"
      sv_templates true
      service_mirror # Declared in 
    
    service("opscode-push-jobs-client") do
      provider Chef::Provider::Service::Simple
      action [:nothing]
      supports {:restart=>true, :reload=>true, :status=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "opscode-push-jobs-client"
      pattern "opscode-push-jobs-client"
      start_command "/sbin/sv start /etc/service/opscode-push-jobs-client"
      stop_command "/sbin/sv stop /etc/service/opscode-push-jobs-client"
      status_command "/sbin/sv status /etc/service/opscode-push-jobs-client"
      restart_command "/sbin/sv restart /etc/service/opscode-push-jobs-client"
    end
    
      declared_type :runit_service
      cookbook_name "push-jobs"
      recipe_name "service_runit"
    end
    

Running handlers:
[2015-04-26T19:29:21+09:00] ERROR: Running exception handlers
Running handlers complete
[2015-04-26T19:29:21+09:00] ERROR: Exception handlers complete
[2015-04-26T19:29:21+09:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 21 resources updated in 164.836707763 seconds
[2015-04-26T19:29:21+09:00] ERROR: Chef::Exceptions::MultipleFailures
[2015-04-26T19:29:21+09:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
[root@push-chef12-target2 ~]# 
[root@push-chef12-target2 ~]# /sbin/sv start /etc/service/opscode-push-jobs-client
ok: run: /etc/service/opscode-push-jobs-client: (pid 2589) 66s


 ps -ef | grep push
root      2587  2559  0 19:28 ?        00:00:00 runsv opscode-push-jobs-client
root      2588  2587  0 19:28 ?        00:00:00 svlogd -tt /var/log/opscode-push-jobs-client
root      2589  2587  0 19:28 ?        00:00:00 /opt/opscode-push-jobs-client/embedded/bin/ruby /opt/opscode-push-jobs-client/bin/pushy-client -c /etc/chef/push-jobs-client.rb
root      2610  1576  0 19:31 pts/0    00:00:00 grep push

**Comment by chewi** [comment]
I'm seeing `No resource or method named action_start` on CentOS 7 too.

**Comment by cmluciano** [comment]
Can you provide more info into your cookbook.

**Comment by docwhat** [comment]
I've gotten the `warning: /etc/service/fubar: unable to open supervise/ok: file does not exist` on RHEL 6 before...

This is probably because the `/etc/service/` directory is symlinked and then `sv start` is attempted before `runsvdir` realizes that the symlink is there and starts `runsv`.

`runsv` is what creates the `supervise/ok` pipe and listens on it.

I'm not sure what the right thing is to do... wait until `/etc/service/fubar/supervise/ok` exists?  Or just assume that it will start as soon as `runsv` is launched?

**Comment by docwhat** [comment]
BTW:  A second run should work.  If it doesn't then that is something *other* than I what I described, in which case I'll make a new issue for mine.

**Comment by chewi** [comment]
@docwhat I've been getting that problem too but I thought that the recent 1ea3e60fed82e1e98fd0c458d09d22390b81245e commit would fix that. I haven't tried it yet, have you?

**Comment by docwhat** [comment]
@chewi what version of the cookbook is it in?

**Comment by chewi** [comment]
@docwhat It's not been released yet so I guess you haven't.

**Comment by kplimack** [comment]
this happens on centos 6.x as well.  it has to do with the commands being generated wrong.  runit takes the service name as an argument, not the full path.
```
[root@default-centos-65 ~]# sv  restart /etc/service/berks-api
fail: /etc/service/berks-api: runsv not running
[root@default-centos-65 ~]# sv  restart berks-api
ok: run: berks-api: (pid 12426) 0s
```

**Comment by chewi** [comment]
@kplimack, sorry but sv does take a path. In your example above, you probably need to give `/etc/sv/berks-api` instead. runit makes heavy use of symlinks. Unfortunately I've forgotten the details of the original issue but `:up` has been working for me.

**Comment by kplimack** [comment]
then can you look at the example i pasted and explain why it works the
wrong way?

**Comment by chewi** [comment]
I'm not sure what you mean but you can just give the service name if it's a system-wide service, i.e. one located in `/etc/sv`. If it's a per-user service in some other directory then you have to give a path, either an absolute or relative one.

**Comment by cwjohnston** [comment]
I believe this discussion pertains to version 1.6.0. We now run integration tests on centos 7. Please feel free to open a new issue with steps to reproduce if you still have a problem using the latest release of this cookbook.
