### ISSUE TITLE
Restart fails

### ISSUE THREAD

**Issue by maf23** [hw-cookbooks/runit#120]
I have a problem when our cookbook sends a restart to the runit_service. I get:
NoMethodError: No resource or method named `action_restart' for `Chef::Provider::RunitService ""'

Looking through the code I don't see any 'action :restart' in libraries/provider_runit_service.rb
Shouldn't there be one or am I missing something obvious?

**Comment by jtimberman** [comment]
@maf23 See commit 2c35e72 in #121.
