### ISSUE TITLE
Waiting for service sockets broken

### ISSUE THREAD

**Issue by coderanger** [hw-cookbooks/runit#136]
This was broken during the big refactor https://github.com/hw-cookbooks/runit/blob/develop/libraries/provider_runit_service.rb#L246-L249

Previously the `runit_service` provider code correctly waited for runsv to actually recognize the new service. This was removed and I don't see that the functionality was added elsewhere.

**Comment by coderanger** [comment]
Ping @someara.

**Comment by someara** [comment]
Looks good... I'll look at glueing it in when I have proper internets later this week.

**Comment by mfischer-zd** [comment]
+1, please fix ASAP
