### ISSUE TITLE
Semver, 1.7.0, and ENV files

### ISSUE THREAD

**Issue by tas50** [hw-cookbooks/runit#144]
I'll start by saying thank you for the many Heavy Water cookbooks I've used over the years.  I've saved a ton of time over my career using your work. I'm not angry or unappreciative, but more concerned for the safety of others. It's open source and as such the burden of testing and maintenance is on me and I probably should have read through all the specific changes before I the 1.7.0 release out.

That being said the 1.7.0 release killed my environment and will probably continue to do so for others.  The refactor to a LWRP from a collection of libraries was a monumental change that was done at the same time that behavior changed.  Those changes would be fine if A) it was spelled out in the changelog how large of a change this was and B) the cookbook was rev'd to 2.0.  A huge portion of the Chef community depends on this cookbook and most people seem to set their deps to 1.X.

In the refactor to a LWRP a new bit of functionality was added that deleted runit ENV files not managed by the LWRP (https://github.com/hw-cookbooks/runit/blob/develop/libraries/provider_runit_service.rb#L153).  This was an entirely new feature, which could not be turned off and wasn't mentioned in the changelog.  The deletion also occurred via a Ruby block so no backups of the files were taken before they were deleted.  I rolled the 1.7 release out to a good number of systems that did not include additional ENV files and found no issues with the changes.  As I pushed the changes to my DJBDNS hosts all ENV files for DJBDNS were deleted which completely deleted the config for the service.  Afterwards the services were restarted and all of my internal DNS and external name resolution stopped.  At that point access to my systems became fairly difficult (LDAP w/o DNS == no fun), and the customer facing portion of the application failed as name resolution to key resources the application used failed.  I managed to roll back the dep to the 1.6.0 release, but since the files weren't actually managed by Chef this didn't do anything.  After determining which files were there and what they included I managed to recreate the proper ENV files and return DNS resolution to normal, but not before a pretty painful outage.

There were certainly some important life lessons here such as not trusting why-run and not assuming execution on one type of system equals safety on all.  I still can't help but think that this whole thing could be avoided with a semver bump and a more verbose changelog.   1.7.0 is a fairly new release and a lot of people are going to run into this same issue as the new release gets pulled in for other cookbooks. The env pruning functionality needs to get removed.  If it comes back it needs to be the non-default functionality of the LWRP.  Until then the 1.7.0 release needs to get pulled to prevent blowing away further setups.

**Comment by calebhailey** [comment]
@tas50 - first off let me say - on behalf of everyone at Heavy Water - we're very sorry that you were negatively impacted by these changes. In hindsight, we wholeheartedly agree with your comments. We had initially anticipated a major version bump for these changes, but somehow a last minute discussion with the community resulted in an oversight that we now regret. 

Unfortunately, the remedy isn't as obvious as it may appear - the process of yanking releases isn't simple, and it can introduce other problems. In our experience, it's always better to roll forward - and to your point, the users who are susceptible to these changes are those who have set their deps to 1.x, so a new 1.7.x release to address the issues you've identified should get picked up by those same users. 

Please note our plans to address the issues you've identified: 

- [ ] make the environment cleanup behavior "opt-in" via configuration
- [ ] update CHANGELOG & README to better indicate the severity of changes from 1.6.x -> 1.7.x 
- [ ] update README to indicate that versions 1.7.0 and 1.7.2 are potentially dangerous in certain environments 
- [ ] cut a new 1.7.4 release containing the "opt-in" environment cleanup behavior, as well as other bugfixes - which will also be documented in the CHANGELOG
- [ ] send MOAR #hugops 

@tas50 - thank you again for your candid feedback, and to the entire community for its contributions to our cookbooks over the years. We trust that all members of our community understand the amount of effort that is required to maintain a single community cookbook, let alone the large number of cookbooks that Heavy Water has maintained throughout the years. **It is a LOT of work**, we invest a _lot of time_ on trying to get it right, and sometimes we fall short. 

For some time now, our acute awareness of this reality has been motivating us to rethink our workflow, process, and tooling around developing and maintaining Chef cookbooks. We have made some exciting progress in this regard and are looking forward to sharing it with the community in the coming weeks. 

In the interim, please let us know if you have any questions, comments, suggestions, or objections to the above stated remedy to this issue. 

PS - we owe you a :beer: :)

**Comment by cwjohnston** [comment]
Added cautionary notes to README and CHANGELOG in https://github.com/hw-cookbooks/runit/pull/157

**Comment by cwjohnston** [comment]
I am preparing to cut a new release that adds the `manage_env_dir` attribute (see #152) but now I'm a little confused.

In preparing the changelog I began reviewing commit history and found that env dir cleanup was initially added in #81 and shipped in 1.6.0, but the changes in implementation of this feature between 1.6.0 and 1.7.0 seem significant.

@tas50  Before rolling out 1.7.0 to your environment, were you on version 1.6.0 or ~> 1.5.0 ?

**Comment by cwjohnston** [comment]
Ah I think I see now. The condition at https://github.com/hw-cookbooks/runit/blob/v1.6.0/libraries/provider_runit_service.rb#L108 guards the env files from being cleaned up when the env hash is empty, whereas the refactor released in 1.7.0 runs cleanup unconditionally.

**Comment by cwjohnston** [comment]
The `manage_env_dir` attribute feature has been reverted in favor of fixing what was actually a regression from v1.6.0. See #158 for details.

**Comment by cwjohnston** [comment]
Documentation updates and environment regression fix shipped in v1.7.4
