### ISSUE TITLE
Why for debian runit uses separate template?

### ISSUE THREAD

**Issue by jsirex** [hw-cookbooks/runit#162]
It is not clear for me why debian/init.d.erb exists?
I testes symlinking on debian:
```bash
ln -s /usr/bin/sv /etc/init.d/my-service
```
And it seems to work.
If there is a reason for this, then we missing some actions, like force-stop and kill.

**Comment by jsirex** [comment]
Up

**Comment by cwjohnston** [comment]
Per #5 where this template was introduced:

> Debian's update-rc.d directly attempts to read the header of each file in /etc/init.d/ via perl. Obviously this isn't going to work when the /etc/init.d/ is a symlink to the sv binary. This holds true for the forthcoming Wheezy release as well as Squeeze, as Debian is not (yet?) moving forward with upstart as an init replacement.
>
