### ISSUE TITLE
runsvdir-start doesn't start inside docker without init

### ISSUE THREAD

**Issue by jsirex** [hw-cookbooks/runit#163]
In docker container runsvdir-start doesn't start (at least for debian).

The root cause of issue is init system inside container.

Package `runit` relays on `/etc/inittab` with:
```
#-- runit begin
SV:123456:respawn:/usr/sbin/runsvdir-start
#-- runit end
```
Then it send HUP signal to process with pid 1. 
Under test-kitchen pid 1 is sshd. So there are no way to start runit using only package.

**Comment by xmik** [comment]
If you want to use runit in docker, it seems more correct to use [phusion/baseimage-docker](https://github.com/phusion/baseimage-docker) as base image.

**Comment by jsirex** [comment]
@xmik Looks interesting. I will investigate this container.
Thanks.

**Comment by jsirex** [comment]
@xmik This is an ubunutu image. I need debian. But I think it should work for any debian container.
