### ISSUE TITLE
CONTRIBUTING.md documentation is out of date

### ISSUE THREAD

**Issue by cnmcavoy** [hw-cookbooks/runit#165]
The contribution readme documentation appears to be out of date. It links to the Chef JIRA (which has been deprecated for some time now). Also, are the CLA for opscodes truly a requirement for contributing to hw-cookbooks? It appears as though the contributing.md file was reused from an official chef codebase. Other hw-cookbooks (like graphite) have a completely different contributing readme.

**Comment by cwjohnston** [comment]
Fixed in `develop` by #161 and #168
