### ISSUE TITLE
It's time to remove support for Ubuntu 8.04

### ISSUE THREAD

**Issue by tas50** [hw-cookbooks/runit#178]
There's a ton of cruft in the default recipe that relates to LONG ago deprecated releases of Debian and Ubuntu.  Things could be greatly simplified by removing a lot of this logic. If anyone out there is still relying on Chef to run their Ubuntu 8.04 infrastructure I highly doubt they're pulling in the latest and greatest runit cookbook so this has a 0 chance of hurting anyone.

**Comment by martinisoft** [comment]
Would agree there. Ubuntu < 11.10 can be safely deprecated at this point.

**Comment by martinisoft** [comment]
Sent a PR to show what this looks like.
