### ISSUE TITLE
Tighten env_files permissions

### ISSUE THREAD

**Issue by smith** [hw-cookbooks/runit#54]
In the [env_files method](https://github.com/hw-cookbooks/runit/blob/bf0c2428b2c0c344c650108a82c9ab2a55d54626/libraries/provider_runit_service.rb#L408-L418) the files that get created use the default permissions of 0644.

Environment variables used by a service may contain secrets, so it might be better to create these files with 0600 or 0660 permissions in order to prevent other users on the system from reading sensitive data.

**Comment by cwjohnston** [comment]
Closed by #125
