### ISSUE TITLE
waiting until named pipe shall have a timeout

### ISSUE THREAD

**Issue by jpoutrin** [hw-cookbooks/runit#56]
For some reason sometimes a service is suppose to have a named piped created but it does not work. 

exemple:
 waiting until named pipe /etc/service/nginx/supervise/ok exists.

This should fail after a certain amount of time as now it hangs forever.

**Comment by cwjohnston** [comment]
I'm closing this issue as I believe our documentation change in #193 indicates the requirements for running this cookbook in a docker container.
