### ISSUE TITLE
runit 2.1.2

### ISSUE THREAD

**Issue by jtimberman** [hw-cookbooks/runit#64]
Via the supervision mailing list, Gerrit Pape has updated runit to version 2.1.2.

```
version 2.1.2 of the runit package is available for through

 http://smarden.org/runit/

The sv program learns the LSB init script actions reload and
try-restart.  It also fixes two bugs that lead to wrong or badly
formatted output under some circumstances when reporting status of
services, and its documentation now properly states that on exit no
TERM signal is sent to the optional log service, but its standard
input is closed.
```

What this means for the cookbook is that the [runit-2.1.1.tar.gz packaging](https://github.com/hw-cookbooks/runit/tree/master/files/default) needs to be updated.

**Comment by jtimberman** [comment]
Per 1.6.0 and comment in #65, on RHEL we use packagecloud repo for installation.

**Comment by slyness** [comment]
@jtimberman I had some issues with emeril pushing this latest version up to supermarket. that's why 1.6.0 hasn't quite made it up there yet. Hopefully, I can get back to that asap and get this version really released.

**Comment by jtimberman** [comment]
@slyness I used stove to publish 1.6.0 yesterday. :smile_cat:

**Comment by slyness** [comment]
@jtimberman awesome!
