### ISSUE TITLE
log_size not honored when using default_logger

### ISSUE THREAD

**Issue by javamonkey79** [hw-cookbooks/runit#75]
If both of these are set:
  default_logger true
  log_size 50000000

The log_size property is not honored.

I think this is because the log config file is being placed in:
/etc/sv/#{service-name}/log

Instead of /var/log/#{service-name}

**Comment by mkropat** [comment]
I'm also running into this issue.  There's a pull request (#47) to deal with it, although it looks like it's stalled out.

**Comment by slyness** [comment]
Resolved.
