### ISSUE TITLE
Review and Update Test Coverage

### ISSUE THREAD

**Issue by slyness** [hw-cookbooks/runit#80]
Currently using mini-test Chef Handler to run tests. We should use Serverspec and Chefspec for tests.

**Comment by jtimberman** [comment]
An checklist!

* [ ] ChefSpec coverage for conditional branching
* [ ] ServerSpec for post convergence verification
* [ ] Remove minitest-chef-handler usage

We have resource/provider unit test coverage already.

**Comment by cwjohnston** [comment]
All of the above are handled by #107! :tada:
