### ISSUE TITLE
Switch RHEL to use imeyer's packagecloud repo

### ISSUE THREAD

**Issue by jtimberman** [hw-cookbooks/runit#88]
The build-from-source part of the default recipe for RHEL uses @imeyer's [runit-rpm](https://github.com/imeyer/runit-rpm). We should switch to using his [Package Cloud repository](https://packagecloud.io/imeyer/runit) entirely and remove the "[rhel_build_install](https://github.com/hw-cookbooks/runit/blob/develop/recipes/default.rb#L67)" resource.

**Comment by jtimberman** [comment]
@slyness thoughts?

**Comment by slyness** [comment]
@jtimberman I think this is a fantastic idea. I was working with that build stuff the other day and I was thinking. this isn't ideal. Let's move to the repo packages. Do you have time to take this as a task or would you rather....... have me knock it out..

**Comment by jtimberman** [comment]
I might have cycles in the next couple days. This will be a lot easier to deal with and test than the current situation.

**Comment by jtimberman** [comment]
Implemented as https://github.com/hw-cookbooks/runit/pull/91
