### ISSUE TITLE
runit_service doesn't respect custom sv_bin on Debian

### ISSUE THREAD

**Issue by lebrinkma** [hw-cookbooks/runit#92]
On Debian the init.d file created by runit_service hardcodes the sv_bin to /usr/bin/sv.
This breakes runit when there is no sv in /usr/bin.
The scriptname is also hardcoded to /etc/init.d/

See https://github.com/hw-cookbooks/runit/blob/53049a01ca40c166ba54cd19f643f086975fe207/templates/debian/init.d.erb#L16-17

I will make a PR that fixes this issue.

**Comment by lebrinkma** [comment]
This bug is still present. see #98.

**Comment by lebrinkma** [comment]
@slyness This bug has to be reopend.
The fixing commit somehow got removed and is not present in develop or master anymore.

**Comment by slyness** [comment]
@lebrinkma that's strange. re-opening issue.

**Comment by cwjohnston** [comment]
Fix in #123
